name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: DOCKER_HUB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: GOPATH="." GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go get

      - name: Build
        run: GOPATH="." GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o build/go-reverseproxy-ssl .

      - name: Test
        run: go test -v ./...
        

